import { CalendarClock, CheckCircle2, ChevronRight, Clock3, MessageCircle, Phone, Search, Send, SlidersHorizontal, UserRound, XCircle } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { PageHeading, StatusPill } from "@/components/SkillioShell";

export default function FollowUps() {
  const [tab, setTab] = useState("Needs attention");
  const [query, setQuery] = useState("");
  const [sent, setSent] = useState<string[]>([]);
  const utils = trpc.useUtils();
  const queueQuery = trpc.followUps.queue.useQuery();
  const traineesQuery = trpc.outcomes.trainees.useQuery();
  const activityQuery = trpc.followUps.activity.useQuery();
  const sendMessageMutation = trpc.followUps.sendMessage.useMutation({
    onSuccess: (result) => {
      setSent((current) => (current.includes(result.caseId) ? current : [...current, result.caseId]));
      toast.success(result.duplicate ? "Outreach already queued today" : "Outreach queued for delivery");
      void utils.followUps.activity.invalidate();
    },
    onError: (error) => toast.error(error.message),
  });

  const traineeById = useMemo(() => {
    const map = new Map<string, { name: string; initials: string; course: string; district: string }>();
    for (const trainee of traineesQuery.data ?? []) {
      map.set(trainee.id, { name: trainee.name, initials: trainee.initials, course: trainee.course, district: trainee.district });
    }
    return map;
  }, [traineesQuery.data]);

  const queue = queueQuery.data ?? [];
  const dueToday = queue.filter((item) => item.due === "Today").length;
  const urgent = queue.filter((item) => item.priority === "P1").length;
  const needsAttention = queue.filter((item) => item.priority !== "P3").length;
  const visible = queue.filter((item) => {
    const trainee = traineeById.get(item.traineeId);
    return `${item.title} ${item.reason} ${trainee?.name ?? ""}`.toLowerCase().includes(query.toLowerCase()) && (tab === "All activity" || (tab === "Needs attention" ? item.priority !== "P3" : item.priority === "P3"));
  });
  const sendMessage = (id: string) => sendMessageMutation.mutate({ caseId: id, channel: "WhatsApp" });
  return <div className="mx-auto max-w-[1280px]"><PageHeading eyebrow="Follow-up operations" title="Turn unanswered signals into action." description="Automation handles routine reach. Counsellors handle ambiguity, barriers, and the moments where a person needs support." action={<Button className="h-10 gap-2 rounded-xl bg-[#0f766e] text-xs hover:bg-[#0b625c]"><CalendarClock className="h-3.5 w-3.5" />Schedule campaign</Button>} />
    <div className="mb-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-[#eadfc7] bg-[#fffaf0] p-4"><div className="flex items-center justify-between"><span className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#a56e18]">Due today</span><Clock3 className="h-4 w-4 text-[#c28b32]" /></div><p className="mt-2 text-2xl font-semibold tracking-[-0.06em] text-[#153633]">{dueToday}</p><p className="mt-1 text-[11px] text-slate-500">cases with a due date of today</p></div><div className="rounded-2xl border border-[#ccebe1] bg-[#edf9f4] p-4"><div className="flex items-center justify-between"><span className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#4a927f]">Urgent (P1)</span><CheckCircle2 className="h-4 w-4 text-[#278271]" /></div><p className="mt-2 text-2xl font-semibold tracking-[-0.06em] text-[#153633]">{urgent}</p><p className="mt-1 text-[11px] text-slate-500">cases needing same-day action</p></div><div className="rounded-2xl border border-[#dfd7f3] bg-[#f7f4fd] p-4"><div className="flex items-center justify-between"><span className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#7457aa]">Open cases</span><MessageCircle className="h-4 w-4 text-[#7457aa]" /></div><p className="mt-2 text-2xl font-semibold tracking-[-0.06em] text-[#153633]">{queue.length}</p><p className="mt-1 text-[11px] text-slate-500">in the counsellor queue</p></div></div>
    <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-1 rounded-xl bg-slate-100 p-1"><button onClick={() => setTab("Needs attention")} className={`rounded-lg px-3 py-2 text-[11px] font-semibold ${tab === "Needs attention" ? "bg-white text-[#153633] shadow-sm" : "text-slate-500"}`}>Needs attention <span className="ml-1 text-[#b65348]">{needsAttention}</span></button><button onClick={() => setTab("All activity")} className={`rounded-lg px-3 py-2 text-[11px] font-semibold ${tab === "All activity" ? "bg-white text-[#153633] shadow-sm" : "text-slate-500"}`}>All activity</button><button onClick={() => setTab("Unreachable")} className={`rounded-lg px-3 py-2 text-[11px] font-semibold ${tab === "Unreachable" ? "bg-white text-[#153633] shadow-sm" : "text-slate-500"}`}>Unreachable</button></div><div className="flex gap-2"><div className="relative"><Search className="absolute left-3 top-2.5 h-3.5 w-3.5 text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search cases" className="h-9 w-full rounded-lg border border-slate-200 bg-white pl-8 pr-3 text-xs outline-none focus:ring-2 focus:ring-[#dff2eb] sm:w-[220px]" /></div><Button variant="outline" className="h-9 gap-2 rounded-lg border-slate-200 bg-white text-xs text-slate-600"><SlidersHorizontal className="h-3.5 w-3.5" />Filters</Button></div></div>
    <Card className="border-slate-200/80 bg-white shadow-[0_8px_28px_rgba(24,52,48,0.035)]"><CardHeader className="pb-2"><CardTitle className="text-sm font-semibold text-[#153633]">Counsellor queue</CardTitle><p className="mt-1 text-xs text-slate-400">Prioritised by urgency, evidence conflict, and trainee request</p></CardHeader><CardContent className="space-y-3">{queueQuery.isLoading ? <p className="py-8 text-center text-xs text-slate-400">Loading the counsellor queue…</p> : visible.length === 0 ? <p className="py-8 text-center text-xs text-slate-400">No cases match the current view.</p> : visible.map((item) => { const trainee = traineeById.get(item.traineeId); const messageSent = sent.includes(item.id); return <div key={item.id} className="grid gap-4 rounded-2xl border border-slate-100 p-4 transition-colors hover:border-[#ccebe1] lg:grid-cols-[1.5fr_1.5fr_1fr_auto] lg:items-center"><div className="flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#e6f0ed] text-xs font-bold text-[#247563]">{trainee?.initials ?? "—"}</div><div><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-semibold text-slate-700">{trainee?.name ?? item.traineeId}</p><StatusPill tone={item.priority === "P1" ? "rose" : item.priority === "P2" ? "amber" : "neutral"}>{item.priority}</StatusPill></div><p className="mt-1 text-[11px] text-slate-400">{trainee ? `${trainee.course} · ${trainee.district}` : "Trainee details unavailable"}</p></div></div><div><p className="text-xs font-semibold text-slate-700">{item.title}</p><p className="mt-1 text-[11px] leading-4 text-slate-500">{item.reason}</p></div><div><p className="text-[10px] uppercase tracking-[0.12em] text-slate-400">Next best action</p><p className="mt-1 text-[11px] font-semibold text-[#278271]">{item.nextAction}</p><div className="mt-1 flex items-center gap-1 text-[10px] text-slate-400">{item.channel === "WhatsApp" ? <MessageCircle className="h-3 w-3" /> : item.channel === "SMS" ? <Send className="h-3 w-3" /> : <Phone className="h-3 w-3" />}{item.channel} · {item.due}</div></div><div className="flex gap-2 lg:justify-end">{item.channel !== "Call" ? <Button onClick={() => sendMessage(item.id)} variant={messageSent ? "outline" : "default"} className={`h-8 rounded-lg px-3 text-[10px] ${messageSent ? "border-[#b8e3d5] text-[#278271]" : "bg-[#0f766e] hover:bg-[#0b625c]"}`}>{messageSent ? <><CheckCircle2 className="mr-1.5 h-3.5 w-3.5" />Queued</> : <><Send className="mr-1.5 h-3.5 w-3.5" />Send</>}</Button> : <Button variant="outline" className="h-8 rounded-lg border-slate-200 px-3 text-[10px]"><Phone className="mr-1.5 h-3.5 w-3.5" />Call</Button>}<Link href={`/trainees/${item.traineeId}`}><Button variant="ghost" size="icon" className="h-8 w-8 rounded-lg text-slate-400"><ChevronRight className="h-4 w-4" /></Button></Link></div></div>; })}</CardContent></Card>
    <div className="mt-4 grid gap-4 lg:grid-cols-[1fr_360px]"><Card className="border-slate-200/80 bg-white shadow-[0_8px_28px_rgba(24,52,48,0.035)]"><CardHeader className="pb-2"><CardTitle className="text-sm font-semibold text-[#153633]">Message activity</CardTitle><p className="mt-1 text-xs text-slate-400">Provider-neutral delivery events with no raw message content</p></CardHeader><CardContent className="space-y-3">{activityQuery.isLoading ? <p className="py-8 text-center text-xs text-slate-400">Loading message activity…</p> : (activityQuery.data ?? []).length === 0 ? <p className="py-8 text-center text-xs text-slate-400">No messages sent yet. Queue actions will appear here.</p> : (activityQuery.data ?? []).map((attempt) => { const Icon = attempt.channel === "whatsapp" ? MessageCircle : Send; return <div key={attempt.id} className="flex items-center gap-3"><div className={`flex h-8 w-8 items-center justify-center rounded-lg ${attempt.tone === "teal" ? "bg-[#e1f4ed] text-[#278271]" : attempt.tone === "amber" ? "bg-[#fbf0d9] text-[#a56e18]" : "bg-[#fce8e5] text-[#b65348]"}`}><Icon className="h-4 w-4" /></div><div className="min-w-0 flex-1"><p className="text-xs font-semibold text-slate-700">{attempt.channel.toUpperCase()} · {attempt.status}</p><p className="mt-0.5 truncate text-[10px] text-slate-400">{attempt.templateCode} · {attempt.traineeRef}</p></div><span className="shrink-0 text-[10px] text-slate-400">{attempt.date}</span></div>; })}</CardContent></Card><Card className="border-[#ccebe1] bg-[#edf9f4] shadow-[0_8px_28px_rgba(24,52,48,0.035)]"><CardHeader className="pb-2"><CardTitle className="text-sm font-semibold text-[#153633]">Automation rule</CardTitle></CardHeader><CardContent><p className="text-xs leading-5 text-slate-600">After two unanswered reminders, Skillio creates a counsellor case. If WhatsApp delivery fails, SMS becomes the fallback only when consent scope allows it.</p><div className="mt-4 flex items-center gap-2 text-[11px] font-semibold text-[#278271]"><UserRound className="h-3.5 w-3.5" />Human review stays in the loop</div></CardContent></Card></div>
  </div>;
}
