import { ArrowUpRight, CheckCircle2, ChevronRight, CircleAlert, Layers3, MapPin, Sparkles, Users } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { PageHeading, StatusPill } from "@/components/SkillioShell";

export default function SkillGaps() {
  const [resolved, setResolved] = useState<string[]>([]);
  const gapsQuery = trpc.outcomes.skillGaps.useQuery();
  const gaps = gapsQuery.data ?? [];
  const totalSignals = gaps.reduce((sum, gap) => sum + (gap.affectedCount ?? 0), 0);
  return <div className="mx-auto max-w-[1180px]"><PageHeading eyebrow="Skill-gap intelligence" title="Turn barriers into curriculum action." description="Skillio combines trainee responses, employer verification, and course context to surface the gaps that deserve a practical response." action={<Button className="h-10 gap-2 rounded-xl bg-[#0f766e] text-xs hover:bg-[#0b625c]"><Sparkles className="h-3.5 w-3.5" />Run signal refresh</Button>} />
    <div className="mb-6 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl bg-[#0d2928] p-5 text-white"><p className="text-[10px] font-bold uppercase tracking-[0.15em] text-[#8fb8ae]">Trainee signals</p><p className="mt-2 text-3xl font-semibold tracking-[-0.07em]">{gapsQuery.isLoading ? "…" : totalSignals}</p><p className="mt-1 text-[11px] text-white/55">Across {gaps.length} reported barriers</p></div><div className="rounded-2xl border border-[#eadfc7] bg-[#fffaf0] p-5"><p className="text-[10px] font-bold uppercase tracking-[0.15em] text-[#a56e18]">Barriers detected</p><p className="mt-2 text-3xl font-semibold tracking-[-0.07em] text-[#153633]">{gapsQuery.isLoading ? "…" : gaps.length}</p><p className="mt-1 text-[11px] text-slate-500">Grouped from trainee responses</p></div><div className="rounded-2xl border border-[#ccebe1] bg-[#edf9f4] p-5"><p className="text-[10px] font-bold uppercase tracking-[0.15em] text-[#4a927f]">Actions in progress</p><p className="mt-2 text-3xl font-semibold tracking-[-0.07em] text-[#153633]">{resolved.length}</p><p className="mt-1 text-[11px] text-slate-500">Marked from this board</p></div></div>
    {gapsQuery.isLoading ? <Card className="border-slate-200/80 bg-white shadow-[0_8px_28px_rgba(24,52,48,0.035)]"><CardContent className="p-8 text-center text-xs text-slate-400">Loading skill-gap signals…</CardContent></Card> : gaps.length === 0 ? <Card className="border-slate-200/80 bg-white shadow-[0_8px_28px_rgba(24,52,48,0.035)]"><CardContent className="p-8 text-center text-xs text-slate-400">No barriers reported yet. Signals appear as trainees respond to follow-ups.</CardContent></Card> : <div className="grid gap-4 lg:grid-cols-3">{gaps.map((gap) => { const done = resolved.includes(gap.id); return <Card key={gap.id} className={`border-slate-200/80 bg-white shadow-[0_8px_28px_rgba(24,52,48,0.035)] ${done ? "opacity-70" : ""}`}><CardHeader className="pb-3"><div className="flex items-start justify-between"><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${gap.severity === "High" ? "bg-[#fce8e5] text-[#b65348]" : gap.severity === "Medium" ? "bg-[#fbf0d9] text-[#a56e18]" : "bg-[#e9f1f8] text-[#557b9f]"}`}><CircleAlert className="h-5 w-5" /></span><StatusPill tone={gap.severity === "High" ? "rose" : gap.severity === "Medium" ? "amber" : "neutral"}>{done ? "In progress" : gap.severity}</StatusPill></div><CardTitle className="mt-4 text-sm font-semibold text-[#153633]">{gap.skill}</CardTitle><p className="mt-1 text-xs leading-5 text-slate-400">{gap.locations}</p></CardHeader><CardContent><div className="space-y-3 border-t border-slate-100 pt-4"><div className="flex items-center gap-2 text-[11px] text-slate-500"><Users className="h-3.5 w-3.5 text-[#278271]" />{gap.affected}</div><div className="flex items-center gap-2 text-[11px] text-slate-500"><Layers3 className="h-3.5 w-3.5 text-[#278271]" />{gap.evidence}</div><div className="flex items-center gap-2 text-[11px] text-slate-500"><MapPin className="h-3.5 w-3.5 text-[#278271]" />Owner: {gap.owner}</div></div><div className="mt-5 rounded-xl bg-[#f6f8f7] p-3"><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-slate-400">Recommended action</p><p className="mt-1 text-xs font-semibold leading-5 text-slate-700">{gap.action}</p></div><Button onClick={() => setResolved((current) => current.includes(gap.id) ? current.filter((id) => id !== gap.id) : [...current, gap.id])} variant={done ? "outline" : "default"} className={`mt-4 h-9 w-full rounded-lg text-xs ${done ? "border-[#b8e3d5] text-[#278271]" : "bg-[#0f766e] hover:bg-[#0b625c]"}`}>{done ? <><CheckCircle2 className="mr-2 h-3.5 w-3.5" />Action in progress</> : <>Assign intervention <ArrowUpRight className="ml-2 h-3.5 w-3.5" /></>}</Button></CardContent></Card>; })}</div>}
    <Card className="mt-5 border-slate-200/80 bg-white shadow-[0_8px_28px_rgba(24,52,48,0.035)]"><CardHeader><CardTitle className="text-sm font-semibold text-[#153633]">How signals become decisions</CardTitle></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-3"><div className="rounded-xl bg-[#f6f8f7] p-4"><p className="text-xs font-semibold text-slate-700">1. Detect</p><p className="mt-1 text-[11px] leading-5 text-slate-500">A recurring barrier appears in a meaningful share of responses.</p></div><div className="rounded-xl bg-[#f6f8f7] p-4"><p className="text-xs font-semibold text-slate-700">2. Corroborate</p><p className="mt-1 text-[11px] leading-5 text-slate-500">Trainee signals are compared with employer or counsellor evidence.</p></div><div className="rounded-xl bg-[#f6f8f7] p-4"><p className="text-xs font-semibold text-slate-700">3. Act</p><p className="mt-1 text-[11px] leading-5 text-slate-500">An owner receives a recommended intervention with a status to track.</p></div></div><div className="mt-4 flex items-center gap-2 text-[11px] text-slate-400"><ChevronRight className="h-3.5 w-3.5" />No black-box ranking. Every card shows the evidence behind the recommendation.</div></CardContent></Card>
  </div>;
}
